title = "Global configrations"

[cloud]
# just support single cloud current
ip = "xxx.xxx.xxx.xxx"
username = "xxx"
password = "xxx"
port = 22


[edges]
info = [
    # ip, username, password, port, connected cloud's ip 
    ["xxx.xxx.xxx.xxx", "xxx","xxx","22","xxx.xxx.xxx.xxx"]
]

[iots]
info = [
    # ip, username, password, port, connected edge's ip 
    ["xxx.xxx.xxx.xxx", "xxx","xxx","22","xxx.xxx.xxx.xxx"]
]
